### ISSUE TITLE
Abstract inequalities constraints

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTBase.jl#122]
Looks like the for `≥` constraints, problem with one-sided case (check the call to the functional code)
![IMG_2649](https://github.com/control-toolbox/CTBase.jl/assets/62183989/4787bd49-a48c-48be-8ce8-1daca6dd41f9)
 
EDIT: should be fixed by [#123]

**Comment by jbcaillau** [comment]
@jbcaillau check this

**Comment by ocots** [comment]
So?

**Comment by jbcaillau** [comment]
See also https://github.com/control-toolbox/CTBase.jl/issues/71

**Comment by PierreMartinon** [comment]
@ocots @jbcaillau No idea if this is related, but I have some problems with inequalities as well: none of the three constraints on the control below are accepted, i get a ParsingError (unknown syntax or bad constraint)
```
@def ocp begin
    t ∈ [ 0, 1], time
    x ∈ R, state
    u ∈ R^2, control
    u_1(t) >= 0
    0 ≤ u_2(t)
	[0,0] ≤ u(t)
```

**Comment by ocots** [comment]
Yes it is!

**Comment by ocots** [comment]
It should be ok with the `v0.10.0` of `CTBase.jl` package.

**Comment by jbcaillau** [comment]
@PierreMartinon yes and no:
- for single sided ineqs, should be `expr <= or >= bound` (not the converse order)
- then it works indeed (bug fixed in `v0.10.0`)
![IMG_3270](https://github.com/control-toolbox/CTBase.jl/assets/62183989/8bd154aa-f57d-4395-acc7-72f2a437c218)

**Comment by PierreMartinon** [comment]
Ok thanks, it works indeed ! 
Still having some problems with the weird characters (subscripts) ...
